[package]
name = "coc"
version = "0.1.0"
authors = ["David Alber <alber.david@gmail.com>"]
edition = "2018"

[dependencies]
handlebars = "1.1.0"
serde = "1.0.83"
serde_derive = "1.0.83"
toml = "0.4.10"
